WebAppOB/Controllers/CancelarCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppOB.Controllers
{
    public class CancelarCompraController : Controller
    {
        // GET: CancelarCompra
        public ActionResult Index()
        {
            if (Session["usuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if(((Dominio.Usuario)Session["usuario"]).Tipo == Dominio.Usuario.EnumTipo.CLIENTE)
            {

            
            Dominio.Sistema sis = Dominio.Sistema.InstanciaSistema;

            Dominio.Usuario u = sis.BuscarUsuario(((Dominio.Usuario)Session["usuario"]).Username, ((Dominio.Usuario)Session["usuario"]).Password);
            Dominio.Cliente cli = sis.BuscarCliente(u);
            ViewBag.Compras = cli.Compras;

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
       
        public ActionResult CancelarCompraCliente(int? codigoCompra)
        {
            if (Session["usuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (((Dominio.Usuario)Session["usuario"]).Tipo == Dominio.Usuario.EnumTipo.CLIENTE)
            {
                Dominio.Sistema sis = Dominio.Sistema.InstanciaSistema;

                Dominio.Usuario u = sis.BuscarUsuario(((Dominio.Usuario)Session["usuario"]).Username, ((Dominio.Usuario)Session["usuario"]).Password);
                Dominio.Cliente cli = sis.BuscarCliente(u);

                List<Dominio.Compra> comprasAuxiliaresCli = new List<Dominio.Compra>();
                List<Dominio.Compra> comprasAuxiliaresSis = new List<Dominio.Compra>();
                foreach (Dominio.Compra comp in cli.Compras)
                {
                    if (comp.Codigo == codigoCompra)
                    {
                        DateTime fecha = DateTime.Today.AddDays(-10);
                        if (fecha > comp.UnaExcursion.FechaComienzo)
                        {
                            //eliminar compra de lista de compras de cliente
                            foreach (Dominio.Compra c in cli.Compras)
                            {
                                if (c.Codigo != codigoCompra)
                                {
                                    comprasAuxiliaresCli.Add(c);
                                }
                            }

                            // eliminar la compra en la lista de compras general.
                            foreach (Dominio.Compra c in sis.Compras)
                            {
                                if (c.Codigo != codigoCompra)
                                {
                                    comprasAuxiliaresSis.Add(c);
                                }
                            }


                            //ajuste de stock
                            foreach (Dominio.Compra c in sis.Compras)
                            {
                                if (c.Codigo == codigoCompra)
                                {
                                    foreach (Dominio.Excursion e in sis.ListaExcursiones)
                                    {
                                        if (e.Codigo == c.UnaExcursion.Codigo)
                                        {
                                            e.Stock += c.CantidadPasajeros;
                                        }
                                    }

                                }
                            }

                            cli.Compras = comprasAuxiliaresCli;
                            sis.Compras = comprasAuxiliaresSis;


                            ViewBag.Compras = cli.Compras;


                        }
                        else
                        {
                            ViewBag.Compras = cli.Compras;
                            ViewBag.error = "Solo se puede cancelar compra hasta 10 dias antes de la fecha de la excursion";
                        }
                    }

                }
                return View("Index");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }


            
            

            
        }
           
    }
}

WebAppOB/Controllers/ClienteController.cs
using System;
using Dominio;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppOB.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            if (Session["usuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (((Dominio.Usuario)Session["usuario"]).Tipo == Dominio.Usuario.EnumTipo.CLIENTE)
            {
                Dominio.Sistema sis = Dominio.Sistema.InstanciaSistema;
                List<Excursion> excursiones = sis.ListaExcursiones;
                ViewBag.Excursiones = excursiones;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
    }
}

WebAppOB/Controllers/ClienteRegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppOB.Controllers
{
    public class ClienteRegistroController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            List<Dominio.Cliente> clientes = Dominio.Sistema.InstanciaSistema.Clientes;

            ViewBag.Clientes = clientes;
            return View();
        }

        [HttpPost]
        public ActionResult AgregarCliente(Dominio.Cliente cli)
        {
            

            Dominio.Sistema.InstanciaSistema.Registrarse(cli.Nombre, cli.Apellido, cli.Cedula, cli.Password);
           

            List<Dominio.Cliente> clientes = Dominio.Sistema.InstanciaSistema.Clientes;

            ViewBag.Clientes = clientes;

            return View("Index");
        }
    }
}

WebAppOB/Controllers/MostrarClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppOB.Controllers
{
    public class MostrarClientesController : Controller
    {
        // GET: MostrarClientes
        public ActionResult Index()
        {
            if (Session["usuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (((Dominio.Usuario)Session["usuario"]).Tipo == Dominio.Usuario.EnumTipo.OPERADOR)
            {
                Dominio.Sistema sis = Dominio.Sistema.InstanciaSistema;
                List<Dominio.Cliente> clientes = sis.Clientes;

                Dominio.OrdenarClienteApellidoYNombre ordenarPorApellidoYNombre = new Dominio.OrdenarClienteApellidoYNombre();


                clientes.Sort(ordenarPorApellidoYNombre);
                ViewBag.Clientes = clientes;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Cliente");
            }
            

            
        }
    }
}

WebAppOB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @*Agrego hoja de estilo de cliente en content css y aqui pongo un link a esa hoja si el usario es cliente*@
    @if (Session["usuario"] != null)
    {
        if ((((Dominio.Usuario)(Session["usuario"])).Tipo) == Dominio.Usuario.EnumTipo.CLIENTE)
        {
            <link href="~/Content/estilosCliente.css" rel="stylesheet" type="text/css" />
        }
        if ((((Dominio.Usuario)(Session["usuario"])).Tipo) == Dominio.Usuario.EnumTipo.OPERADOR)
        {
            <link href="~/Content/estilosOperador.css" rel="stylesheet" type="text/css" />
        }
    }
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    @*prueba boostrap*@
    @*<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>*@
    @*fin prueba boostrap*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["usuario"] == null)
                {
                    @Html.ActionLink("Login", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Registrarse", "Index", "ClienteRegistro", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }

                @if (Session["usuario"] != null)
                {
                    if ((((Dominio.Usuario)Session["usuario"])).Tipo == Dominio.Usuario.EnumTipo.CLIENTE)
                    {
                        @Html.ActionLink("Compra Excursion", "Index", "Cliente", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Cancelacion", "Index", "CancelarCompra", new { area = "" }, new { @class = "navbar-brand" })
                    }
                    if ((((Dominio.Usuario)Session["usuario"])).Tipo == Dominio.Usuario.EnumTipo.OPERADOR)
                    {
                        @Html.ActionLink("Visualizar compras entre fechas", "Index", "ComprasEntreFechas", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Visualizar clientes", "Index", "MostrarClientes", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Visualizar estadisticas", "Index", "VisualizarEstadisticas", new { area = "" }, new { @class = "navbar-brand" })
                       

                    }
                    @Html.ActionLink("Log Out", "LogOut", "Login", new { area = "" }, new { @class = "navbar-brand" })
                }







            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>